apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlm-token-visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlm-token-visualizer
  template:
    metadata:
      labels:
        app: vlm-token-visualizer
    spec:
      containers:
      - name: vlm-token-visualizer
        image: vlm-token-visualizer:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vlm-token-visualizer
spec:
  selector:
    app: vlm-token-visualizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
